# Tests
env:
  RENV_PATHS_ROOT: ~/.local/share/renv
# Test1 : Intro

name: "R Test 1" #name of test
on:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:

    - name: Cache packages
      uses: actions/cache@v1
      with:
        path: ${{ env.RENV_PATHS_ROOT }}
        key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-

    - name: Restore packages
      shell: Rscript {0}
      run: |
        if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
        renv::restore()

    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: '3.5.3' # The R version to download (if necessary) and use.
    # - run: sudo apt-get install libcurl4-openssl-dev
    # - run: Rscript -e 'install.packages(c("tidyr","dplyr","tidyverse","hrbrthemes","tm","proustr","VennDiagram","RColorBrewer","data.table","dplyr","formattable","tidyr"),dependencies=TRUE,repos="http://cran.rstudio.com/")'
    - run: Rscript Code/main.r
    - run: Rscript Code/utils/venn-diagram.r
